---
- name: Download kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: "0755"
  register: kubectl_download
  failed_when: kubectl_download is failed and kubectl_download.msg is not defined
